services:
  db:
    image: postgres:13
    env_file:
      - .env
    container_name: breender-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: breender-app
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
